name: ci
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

env:
  CLANG_TIDY_VERSION: "16.0.0"
  VERBOSE: 1

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        compiler:
          - llvm
        generator:
          - "Ninja"
        build_type:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.1
          target: 'desktop'
          cache: 'true'

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Configure Xmake
        run: |
          xmake f -m ${{matrix.build_type}} --verbose -y

      - name: Build Xmake
        run: |
          xmake -v -j 4

      - name: Unix - Test and coverage
        working-directory: ./build
        run: |
          xmake run --yes --verbose --diagnosis test
